name: Verify Syntax and Readability
on: 
  push:
  workflow_dispatch:
jobs: 
  name: Verify Syntax and Readability
  runs-on: ubuntu-latest
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Install Dependences
      run: npm ci
    - name: Lint with ESLint
      run: npm run lint
      continue-on-error: false
    - name: Build with Webpack
      run: npm run build
      continue-on-error: false