name: Verify Code with ESLint
on: 
  push:
  workflow_dispatch:
jobs: 
  exec-eslint:
    name: Verify using ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Dependences
        run: npm ci
      - name: Lint with ESLint
        run: npm run lint
      - name: Cancel Commit if Issues Found
        run: |
          echo [ ${{ steps }}]
          if [ ${{ steps.eslint.outcome != 'failure' }}]; then
            echo "ESLint found issues. Cancelling commit"
            exit 1
          fi