name: Validate Syntax and Buildability
on: 
  push:
    paths:
      - '.github/workflows/verify-push.yml'
      - 'src/**'
      - '**.js'
      - 'package**'
      - 'tsconfig.json'
  workflow_dispatch:
jobs: 
  execute:
    name: ESLint + Webpack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Dependences
        run: npm ci
      - name: Lint with ESLint
        run: npm run lint:debug
        continue-on-error: false
      - name: Build with Webpack
        run: npm run build
        continue-on-error: false
