name: Verify Syntax and Readability
on: 
  push:
    paths:
      - '.github/workflows/verify-push.yml'
      - 'src/**'
      - '.eslintrc.js'
      - 'package**'
      - 'ts.config.js'
      - 'webpack.config.js'
  workflow_dispatch:
jobs: 
  execute:
    name: Execute ESLint and Webpack Verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Dependences
        run: npm ci
      - name: Lint with ESLint
        run: npm run lint:debug
        continue-on-error: false
      - name: Build with Webpack
        run: npm run build
        continue-on-error: false
